apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elastic-operator
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination: 
    namespace: elastic-system
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/elastic/cloud-on-k8s
    path: deploy/eck-operator
    revision: HEAD
    helm:
      releaseName: eck-operator
      values: |-
        image:
          tag: 1.3.0
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

