apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: argocd
  namespace: argocd
spec:
  host: argo.apps.keith-cluster.perfscale.devcluster.openshift.com
  port:
    targetPort: https
  tls:
    insecureEdgeTerminationPolicy: Redirect 
    termination: passthrough
  to:
    kind: Service
    name: argocd-server
    weight: 100
  wildcardPolicy: None


  